apiVersion: apps/v1
kind: Deployment
metadata: 
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template: 
    metadata: 
      labels:
        app: frontend
    spec: 
      containers:
        - name: users
          image: xebec19/frontend:0.2
          env:  
            - name: TASKS_ADDRESS
              value: tasks-service.default