apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template: 
    metadata: 
      labels:
        app: tasks
    spec: 
      containers:
        - name: users
          image: xebec19/tasks-api:latest
          env:
            - name: AUTH_ADDRESS
              value: auth-service.default
            - name: TASKS_FOLDER
              value: tasks